### ISSUE TITLE
Replace all CIs for GitHub Actions

### ISSUE THREAD

**Issue by santisoler** [fatiando/maintenance#1]
**Description of the desired feature**

After last community call, we decided to move all our automated CIs to GitHub Actions.
Actions work faster than Travis and Azure with much easier configuration, specially for deployment and key managements.
The visualization of the processes is also better because it's integrated into GitHub, including also errors raising on the workflow configuration file, which makes much easier to debug the workflows.

Currently Pooch has already made the change, so we need to do the same on:

- [x] [harmonica](https://github.com/fatiando/harmonica)
- [x] [verde](https://github.com/fatiando/verde)
- [ ] [rockhound](https://github.com/fatiando/rockhound)
- [x] [boule](https://github.com/fatiando/boule)
- [ ] [contributing](https://github.com/fatiando/contributing)

Feel free to open PRs on each repository and ping this issue on it.

**Comment by santisoler** [comment]
Remember to stop saving the docs HTML as build artifacts. See https://github.com/fatiando/boule/pull/58

**Comment by leouieda** [comment]
We opted not to port the contributing CI and rockhound will need a major refactoring anyway so closing this as it's basically done.
