### ISSUE TITLE
Replace versioneer for setuptools-scm

### ISSUE THREAD

**Issue by santisoler** [fatiando/maintenance#4]
**Description**

The new `setuptools-scm` allows to obtain the Semver version of any library through VCS by just installing the `setuptools-scm` package through `pip` or `conda` and then adding some configuration lines on the files used to install the library.
We were already doing the same thing through `versioneer`, although it needed us to copy and paste some large files that don't get automatic updates.

I've already experimented with the replacement on Harmonica, so please take a look at fatiando/harmonica#196 before implementing the same changes on every library.

We know that maintenance tasks are very demanding, so we don't expect a single
person to tackle this issue by themselves. Any help is very welcomed, so please
comment below that you want to take care of the changes on any repository and
we will assign it to you.

**Apply changes to**

Libraries:

- [x] [boule](https://github.com/fatiando/boule)
- [ ] [erizo](https://github.com/fatiando/erizo)
- [x] [harmonica](https://github.com/fatiando/harmonica)
- [x] [pooch](https://github.com/fatiando/pooch)
- [ ] [rockhound](https://github.com/fatiando/rockhound)
- [x] [verde](https://github.com/fatiando/verde)
- [x] [contributing](https://github.com/fatiando/contributing)

**Further instructions**

In order to solve this issue we need to start opening Pull Requests on each
repository listed above. Optionally, we can open Issues on each repository if
further discussion specific to that repository is needed.

Remember to mention this Issue on every Issue or Pull Request opened on each
repository for keeping a record by adding something like:

```
Related to fatiando/maintenance#4
```

A quick checklist:

1. Open an Issue on each repository listed above (optional). Mention this Issue
   on them.
2. Open a Pull Request on the same repository to tackle the Issue. Mention this
   Issue on them.
3. Check-off the repository on the list above once the Pull Request is merged.
4. Close this issue when all items are checked-off.

**Comment by santisoler** [comment]
Worth looking at how @leouieda has solved this in `pooch`: https://github.com/fatiando/pooch/pull/235

**Comment by leouieda** [comment]
Basically done as well since erizo hasn't had any development and I'm not sure it will continue. Same for rockhound, which needs a complete rewrite.
